- name: Install NGINX using DNF
  dnf:
    name: nginx
    state: present

- name: Start and enable NGINX
  service:
    name: nginx
    state: started
    enabled: yes

- name: Open HTTP port (if firewalld is running)
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes
  ignore_errors: yes

- name: Create test page from template
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html

- name: Restart NGINX
  service:
    name: nginx
    state: restarted